version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: dsh-postgres-prod
    hostname: postgres
    env_file: ./.env.production
    volumes:
      - dsh-strapi-data:/var/lib/postgresql/data
    restart: always
    networks:
      - dsh-network

volumes:
  dsh-strapi-data:
    external: true

networks:
  dsh-network:
    external: true
